apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort  # This exposes the service on a specific port on all nodes
  selector:
    app: book-catalog  # This should match the labels in your deployment
  ports:
    - protocol: TCP
      port: 80  # The port that the service will expose within the cluster
      targetPort: 80  # The port that the container is listening on
      nodePort: 30007  # The port on the host machine to access the service (30000-32767 range)
